### ISSUE TITLE
Error calibration data : type FLOAT64

### ISSUE THREAD

**Issue by jbdebelle** [DeGirum/PySDKExamples#47]
Hello thanks for fixing issue #46 but I still get an error.

`File "/venv/lib/python3.10/site-packages/tensorflow/lite/python/optimize/calibrator.py", line 152, in _feed_tensors self._calibrator.FeedTensor(input_array) ValueError: Cannot set tensor: Got value of type FLOAT64 but expected type FLOAT32 for input 0, name: serving_default_images:0 `

I tried to convert the images in the folder to float32 and I still get the same error plus a warning :
`ignoring corrupt image/label: cannot reshape array of size 55 into shape (2)`

Let me know if you have any insights on how to fix this

**Comment by shashichilappagari** [comment]
@khatami-mehrdad Is this issue fixed? if so, can you please cross check with @jbdebelle and close it?

**Comment by khatami-mehrdad** [comment]
@jbdebelle The error you are facing is due to onnx2tf version 1.17.5.
I made a change it our repository which will make sure you have the correct version (onnx2tf>=1.19.12) now.
Please pull [ultralytics_yolov8](https://github.com/DeGirum/ultralytics_yolov8) again and run the same cmd.
It checks and updates onnx2tf to the correct version.
Please let me know if this resolves the issue.
