### ISSUE TITLE
Metrics of full int8 quantized yolov8n-pose with NO separate outputs are all 0

### ISSUE THREAD

**Issue by luca-depe** [DeGirum/PySDKExamples#54]
Hello!  
I tried quantizing a yolov8n-pose model into full int8 with NO separate outputs using [dg_export.py](https://github.com/DeGirum/ultralytics_yolov8/blob/master/dg_export.py) setting `separate_outputs` to `False`. When then using the outputted full int8 quantized model in [dg_val.py](https://github.com/DeGirum/ultralytics_yolov8/blob/master/dg_val.py) and setting again `separate_outputs` to `False` the returned metrics are all zero.  
This is not the case when doing the same process but with `separate_outputs` set to `True`.  

Do you have any explanation on what could be going wrong?

Thank you very much in advance for your help!

**Comment by nklimov23** [comment]
Hello!
 
This problem is related to the normalization of the model output. When a model is exported to fully-quantized int8 TFLite format with separate_outputs=False, bounding box coordinates are normalized by the model input dimensions to bring them into a range of [0, 1]. However, the pose keypoints coordinates have not been normalized. Because the model's output is a tensor that combines both bounding box and keypoint coordinates, the quantization parameters have to be large enough to accomodate both value ranges, [0, 1] for bounding boxes and [0, 640] for keypoints. As a result, the accuracy of this model drops significantly.
This issue originates in the upstream Ultralytics repository. However, we looked into this issue and provided a fix that we recently added to our ultralytics_yolov8 repository at https://github.com/DeGirum/ultralytics_yolov8! You can export the model the same way as you did before. Please, try it out, and let us know if you have any other issues.
